name: build

on:
  workflow_dispatch:
    inputs:
      fake_build:
        description: 'Fake build'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false

env:
  FAKE_BUILD: ${{ github.event.inputs.fake_build }}
  REPO_URL: https://github.com/openwrt-xiaomi/openwrt
  REPO_BRANCH: xq-24.10
  BUILD_ROOT: ${{ github.workspace }}/openwrt
  DEPENDENCIES: ${{ github.workspace }}/dependencies-ubuntu.txt
  TZ: UTC

jobs:
  check:
    runs-on: ubuntu-24.04
    outputs:
      build_date: ${{ steps.gh.outputs.build_date }}
      fw_date: ${{ steps.gh.outputs.fw_date }}
      fw_ver: ${{ steps.gh.outputs.fw_ver }}
    steps:
      - name: Get repo data
        id: gh
        run: |
          BUILD_DATE=$( date --utc +'%y%m%d' )
          FW_DATE=$( date --utc +'%Y-%m-%d' )
          wget $REPO_URL/raw/refs/heads/$REPO_BRANCH/include/version.mk
          FW_VER=$(grep -s '^VERSION_NUMBER:=$(if' version.mk | cut -d"," -f3 | cut -d")" -f1)
          rm -f version.mk
          echo "build_date=$BUILD_DATE" >> $GITHUB_OUTPUT
          echo "fw_date=$FW_DATE" >> $GITHUB_OUTPUT
          echo "fw_ver=$FW_VER" >> $GITHUB_OUTPUT

  build:
    needs: check
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [rd03]
    steps:
      - name: Initialization
        run: |
          sudo apt-get update
          sudo apt-get install -y $(cat $DEPENDENCIES)
          sudo timedatectl set-timezone "$TZ"

      - name: Maximize space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - name: Checkout builder
        uses: actions/checkout@v4

      - name: Download OpenWrt
        run: git clone --branch $REPO_BRANCH $REPO_URL.git $BUILD_ROOT

      - name: Init builder
        run: |
          rsync -avq --exclude=".*" --exclude="openwrt" . $BUILD_ROOT/
          cd $BUILD_ROOT
          chmod +x *.sh
          wget https://github.com/fantastic-packages/packages/raw/refs/heads/24.10/keys/usign/53FF2B6672243D28.pub

      - name: Update packages
        run: cd $BUILD_ROOT && ./xupdate.sh -f

      - name: Build firmware
        env:
          TARGET: ${{ matrix.target }}
          FW_VER: ${{ needs.check.outputs.fw_ver }}
        run: |
          cd $BUILD_ROOT
          MAKE_JOBS=$(($(nproc)+1))
          ./xmake.sh -I -t ${{ matrix.target }}
          [ "$FAKE_BUILD" != "true" ] && make -j $MAKE_JOBS download world
          OUT_DIR=$BUILD_ROOT/bin/targets/*/*
          echo "OUT_DIR=$OUT_DIR" >> $GITHUB_ENV

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-rd03-${{ needs.check.outputs.build_date }}
          path: ${{ env.OUT_DIR }}
          if-no-files-found: error
